version: "3.9"

# 1. BLOCO REUTILIZÁVEL
x-shared-environment: &shared-env
  DOTNET_ENVIRONMENT: Development
  ConnectionStrings__DB_INVEST: "Host=postgres;Port=5432;Database=DB_INVEST;Username=postgres;Password=***"
  RabbitMq__ConnectionUrl: "amqp://guest:***@rabbitmq:5672/"
  AlphaVantage__ApiKey: "***"
  MarketData__BaseUrl: "***"

services:
  invest-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invest-web
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      # 2. VARIÁVEIS COMPARTILHADAS
      <<: *shared-env
      
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"

  invest-worker:
    build:
      context: .
      dockerfile: INVEST.Worker/Dockerfile
    container_name: invest-worker
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    environment:
      <<: *shared-env
      
      EmailSettings__SmtpServer: "smtp.gmail.com"
      EmailSettings__Port: "587"
      EmailSettings__SenderEmail: "seu_email@gmail.com"
      EmailSettings__SenderPassword: "***"

  postgres:
    image: postgres:16
    container_name: invest-postgres
    restart: always
    environment:
      POSTGRES_DB: DB_INVEST
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "***"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: invest-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@invest.com
      PGADMIN_DEFAULT_PASSWORD: "***"
    ports:
      - "5050:80"
    depends_on:
      - postgres
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: invest-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: "***"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
volumes:
  postgres_data:
  rabbitmq_data: