// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INVEST.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("invesT.Data.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AnoEntrada")
                        .HasColumnType("smallint");

                    b.Property<bool>("Estatal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SetorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("invesT.Data.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataRegistro")
                        .HasColumnType("date");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoIndicadorId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ValorBool")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ValorDecimal")
                        .HasColumnType("numeric");

                    b.Property<short?>("ValorShort")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.HasIndex("TipoIndicadorId");

                    b.ToTable("Indicador");
                });

            modelBuilder.Entity("invesT.Data.NivelQualidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("NivelQualidade");
                });

            modelBuilder.Entity("invesT.Data.QualidadeIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelQualidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoIndicadorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NivelQualidadeId");

                    b.HasIndex("TipoIndicadorId");

                    b.ToTable("QualidadeIndicador");
                });

            modelBuilder.Entity("invesT.Data.QualidadeSetor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelQualidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("SetorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NivelQualidadeId");

                    b.HasIndex("SetorId");

                    b.ToTable("QualidadeSetor");
                });

            modelBuilder.Entity("invesT.Data.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("invesT.Data.Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("invesT.Data.TipoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TiposIndicadores");
                });

            modelBuilder.Entity("invesT.Data.Acao", b =>
                {
                    b.HasOne("invesT.Data.Setor", "Setor")
                        .WithMany("Acoes")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("invesT.Data.Indicador", b =>
                {
                    b.HasOne("invesT.Data.Ticker", "Ticker")
                        .WithMany("Indicadores")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("invesT.Data.TipoIndicador", "TipoIndicador")
                        .WithMany("Indicadores")
                        .HasForeignKey("TipoIndicadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticker");

                    b.Navigation("TipoIndicador");
                });

            modelBuilder.Entity("invesT.Data.QualidadeIndicador", b =>
                {
                    b.HasOne("invesT.Data.NivelQualidade", "NivelQualidade")
                        .WithMany()
                        .HasForeignKey("NivelQualidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invesT.Data.TipoIndicador", "TipoIndicador")
                        .WithMany("QualidadeIndicadores")
                        .HasForeignKey("TipoIndicadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelQualidade");

                    b.Navigation("TipoIndicador");
                });

            modelBuilder.Entity("invesT.Data.QualidadeSetor", b =>
                {
                    b.HasOne("invesT.Data.NivelQualidade", "NivelQualidade")
                        .WithMany()
                        .HasForeignKey("NivelQualidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invesT.Data.Setor", "Setor")
                        .WithMany("QualidadeSetores")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelQualidade");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("invesT.Data.Ticker", b =>
                {
                    b.HasOne("invesT.Data.Acao", "Acao")
                        .WithMany("Tickers")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");
                });

            modelBuilder.Entity("invesT.Data.Acao", b =>
                {
                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("invesT.Data.Setor", b =>
                {
                    b.Navigation("Acoes");

                    b.Navigation("QualidadeSetores");
                });

            modelBuilder.Entity("invesT.Data.Ticker", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("invesT.Data.TipoIndicador", b =>
                {
                    b.Navigation("Indicadores");

                    b.Navigation("QualidadeIndicadores");
                });
#pragma warning restore 612, 618
        }
    }
}
